version: "3"

services:
  demo-container-mysq-db:
    image: mysql:8
    container_name: mysql
    #restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: edge2
      MYSQL_USER: finvolv
      MYSQL_PASSWORD: finvolv
    ports:
    - "3306:3306"