version: '3'
services:
  management-center:
    image: hazelcast/management-center:5.3.3
    ports:
    - "8081:8080"
    environment:
    - MC_DEFAULT_CLUSTER=dev
    - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast