# Redis without persisted data
# $ docker-compose -f docker-compose.yml
# 
# to execute redis cli on docker configs:
# $ docker exec -it redis redis-cli


version: '3'

services:
  redis:
    image: 'redis:alpine'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
     - "6379:6379"